version: '3.3'

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: farhod
      POSTGRES_PASSWORD: farhod004
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_URL: postgres://farhod:farhod004@db:5432/mydb
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  postgres_data:
  static_volume:
  media_volume:

