# Generated by Django 4.2.7 on 2024-01-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savat',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savat',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
