# Generated by Django 4.2.7 on 2024-01-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='is_available',
        ),
    ]
